service: automated-settlements

frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-plugin-resource-tagging
  - serverless-deployment-bucket

# useDotenv: true

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs18.x
  region: us-west-2
  memorySize: 128
  environment:
    ENV: ${self:provider.stage}
  stackName: ${self:service}-${self:provider.stage}-stack
  stackTags:
    env: ${self:provider.stage}
    service: ${self:service}.kafene.com
    version: ${file(./package.json):version}
  deploymentBucket:
    name: ${self:service}-${self:provider.stage}-${self:provider.region}-bucket

package:
  individually: true

functions:
  handle-offers:
    handler: src/handler.main
    environment:
      DATADOG_HOST: ${arn:aws:secretsmanager:us-west-2:007745934069:secret:${self:provider.stage}/automated-settlements/lambda-nKiJIY/DATADOG_HOST}
      DATADOG_API_KEY: arn:aws:secretsmanager:us-west-2:007745934069:secret:${self:provider.stage}/automated-settlements/lambda-nKiJIY/DATADOG_API_KEY
      DATADOG_SERVICE: arn:aws:secretsmanager:us-west-2:007745934069:secret:${self:provider.stage}/automated-settlements/lambda-nKiJIY/DATADOG_SERVICE
      BASE_URL: arn:aws:secretsmanager:us-west-2:007745934069:secret:${self:provider.stage}/automated-settlements/lambda-nKiJIY/BASE_URL
      TEST: ${ssm(${self:provider.region}):secret:${self:provider.stage}/automated-settlements}
      
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node18
    define:
      'require.resolve': undefined
    platform: node
    concurrency: 10

